language: android
jdk: oraclejdk8
sudo: required
git:
  depth: 9999
android:
  components:
  - tools
  - platform-tools
  - android-27
  - build-tools-27.0.0
  - extra-android-m2repository
  - extra-google-m2repository
branches:
  except:
  - "/^[0-9]/"
before_install:
- openssl aes-256-cbc -K $encrypted_13d4b12ffe60_key -iv $encrypted_13d4b12ffe60_iv -in firebase-crashreporting-private-key.json.enc -out firebase-crashreporting-private-key.json -d
before_script:
- |
  if [ "$TRAVIS_PULL_REQUEST" != "false" ] && [ "$TRAVIS_BRANCH" = "master" ]; then
    echo "Do not open PRs against master; merge dev into master locally and push instead."
    exit 1
  fi
- export ARTIFACT_VERSION=$(git rev-list --count HEAD)
script:
- case "$TRAVIS_COMMIT_MESSAGE" in
    *"[noci]"*)
      echo "Commit message has [noci]. CI skipped (reported successful)".
      ;;
    *)
      ./gradlew clean build dokka :app:check :domain:check :data:check --no-daemon
      ;;
  esac
after_success:
- |
  if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "master" ] && [[ "$TRAVIS_JOB_NUMBER" == *.1 ]]; then
    echo "CI on master succeded. Executing release tasks..."
    ./ci/release.sh
    echo "Uploading mapping to Firebase..."
    ./gradlew :app:firebaseUploadReleaseProguardMapping
  fi
notifications:
  email:
    recipients:
    - jorge.diazbenitosoriano@gmail.com
    on_success: change
    on_failure: always
